### ISSUE TITLE
This expression is not constructable new Stripe(stripeSecret)

### ISSUE THREAD

**Issue by Any-Winter-4079** [codediodeio/stripe-firebase-master-course#3]
// ENV Variables
export const stripeSecret = functions.config().stripe.secret;

// Export Stripe
import * as Stripe from "stripe";
export const stripe = new Stripe(stripeSecret);

complains (alias) module "stripe"
import Stripe
This expression is not constructable.
  Type 'typeof import("stripe")' has no construct signatures.ts(2351)

**Comment by Grextarosta** [comment]
Hey @eduardoarinopelegrin, after 8.0 types are included in the package and the import thus changes. 

In **config.ts** change the import and export to the following.:

// Export Stripe
import Stripe from 'stripe'; 
export const stripe = new Stripe(stripeSecret, **{
    apiVersion: "2019-12-03",
    typescript: true
}**);

Your tests should now fly through

**Comment by wingtek2020** [comment]
hey guys ty !!!this worked first try

**Comment by Any-Winter-4079** [comment]
Yes, to me this works! Only thing is I had to add the line //@ts-ignore
import Stripe from 'stripe';
export const stripe = new Stripe(stripeSecret, {
//@ts-ignore
apiVersion: "2019-12-03",
typescript: true
});
